[build]
  command = "# no build command needed for static site"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/db-test"
  to = "/.netlify/functions/test-db"
  status = 200
  force = true

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/auth-simple-v2"
  status = 200
  force = true

[[redirects]]
  from = "/api/signup"
  to = "/.netlify/functions/auth-simple-v2"
  status = 200
  force = true

[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200
  force = true

[[redirects]]
  from = "/api/get-random-image"
  to = "/.netlify/functions/game"
  status = 200
  force = true

[[redirects]]
  from = "/api/update-score"
  to = "/.netlify/functions/game"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200