[build]
  command = "# no build command needed for static site"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200